### ISSUE TITLE
Sweep (slow): login function in auth

### ISSUE THREAD

**Issue by Benjaxmen** [Benjaxmen/infinito#39]
### Details

We have all the necessary functions to make a correct login, and we need you to write the details about the difference between login and signin in authentication.md and write the usage of each function.

<details open>
<summary>Checklist</summary>

- [X] `authentication.md` ✅ Commit [`3f90af0`](https://github.com/Benjaxmen/infinito/commit/3f90af0c55ce4b62044507117bc206abfb4c8a0a)
</details>

**Comment by wwzeng1** [comment]
Sweep: retry

**Comment by wwzeng1** [comment]
Sweep: retry

**Comment by wwzeng1** [comment]
Sweep: retry

**Comment by Benjaxmen** [comment]
Sweep: retry
